<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="Harsha" name="com.keylessQE.test.Manager_Settings" tests="1" failures="1"
           timestamp="2021-06-01T17:59:35 IST" time="13.019" errors="0">
    <testcase name="settings" time="13.019" classname="com.keylessQE.test.Manager_Settings">
        <failure type="java.lang.AssertionError" message="The following asserts failed:
	Failed for Located by By.chained({By.AccessibilityId: emailAlerts}) expected [ON] but found [OFF]">
            <![CDATA[java.lang.AssertionError: The following asserts failed:
Failed for Located by By.chained({By.AccessibilityId: emailAlerts}) expected [ON] but found [OFF]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:47)
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:31)
at com.keyless.pages.Account_tab.toggleSettings(Account_tab.java:81)
at com.keyless.pages.Account_tab.toggleEmail(Account_tab.java:85)
at com.keylessQE.test.Manager_Settings.settings(Manager_Settings.java:65)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1257)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.access$000(SuiteRunner.java:28)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:418)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:64)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
]]>
        </failure>
    </testcase> <!-- settings -->
    <system-out>
        <![CDATA[This is the sample screenshot
<a href='/Users/rentlycoimbatore/eclipse-workspace/keyless/Screenshots/null_null_null/2021-06-01-17-58-45/Manager_Settings/settings.png'> <img src='/Users/rentlycoimbatore/eclipse-workspace/keyless/Screenshots/null_null_null/2021-06-01-17-58-45/Manager_Settings/settings.png' height='400' width='400'/> </a>]]>
    </system-out>
</testsuite> <!-- com.keylessQE.test.Manager_Settings -->
